# Generated by Django 3.2.3 on 2021-08-03 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 15, 31, 57, 864767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='aboutMe',
            field=models.TextField(blank=True, verbose_name='о себе'),
        ),
    ]
